---
- name: Checking connectivity
  ping:
    data: alive


- name: Create a directory for openebs
  file:
    path: /root/openebs_config
    state: directory
    mode: 0744
    group: root
    owner: root

#- name: Copy the files to the directory
#  copy:
#    dest: /root/openebs_config
#    src: files/openebs
#    force: true

#- name: Download the chart for openebs
#  get_url:
#    url: https://helmcharts.s3.ir-thr-at1.arvanstorage.ir/openebs.tar
#    dest: /root/openebs_config/

- name: copy the chart to the server
  copy:
    src: files/openebs.tar
    dest: /root/openebs_config/


- name: Unarchive the openebs chart files
  unarchive:
    src: /root/openebs_config/openebs.tar
    dest: /root/openebs_config/
    remote_src: true



- name: Verify if helm is installed on the system
  shell:
    cmd: helm version
  register: helm_check
  failed_when: "'version.BuildInfo' not in helm_check.stdout"
  changed_when: false


- name: Install storage controller on the cluster
  kubernetes.core.helm:
    name: openebs
    create_namespace: true
    chart_ref: /root/openebs_config/openebs
    wait: true
    release_state: present
    values_files: "/root/openebs_config/openebs/values.yaml"
    release_namespace: "openebs"
    set_values:
      - value: cstor.enabled=true
        value_type: string

    atomic: true


- name: Pause for the controller to be set up
  pause:
    seconds: 30




