---
- name: Checking connection
  ping:
    data: alive

- name: Create a directory for Ingress_Controller
  file:
    path: /root/ingress_controller
    owner: root
    group: root
    mode: 0755
    state: directory


- name: Copy the files to the directory
  copy:
    dest: /root/ingress_controller/
    src: files/

- name: Verify if helm is installed on the system
  shell:
    cmd: helm version
  register: helm_check
  failed_when: "'version.BuildInfo' not in helm_check.stdout"
  changed_when: false


- name: Install Ingress controller on the cluster
  kubernetes.core.helm:
    name: ingress-controller
    chart_ref: /root/ingress_controller/nginx-ingress
    release_state: present
    values_files: "/root/ingress_controller/nginx-ingress/values.yaml"
    release_namespace: "ingress-controller"
    create_namespace: true



- name: wait for the probes to be ready
  pause:
    seconds: 40





