---
- name: check connectivity
  ping:
    data: alive

- name: Create a directory for ElasticSearch
  file:
    path: /root/Elasticsearch
    owner: root
    group: root
    mode: 0755
    state: directory


- name: Copy the files to the directory
  copy:
    dest: /root/Elasticsearch/
    src: files/


- name: Create the namespace for Elasticsearch
  kubernetes.core.k8s:
    src: "/root/Elasticsearch/Elastic/Elastic_namespace.yaml"
    state: present
    apply: true
    kubeconfig: /etc/kubernetes/admin.conf

- name: Verify if helm is installed on the system
  shell:
    cmd: helm version
  register: helm_check
  failed_when: "'version.BuildInfo' not in helm_check.stdout"
  changed_when: false

- name: Installing Elastic search on the cluster
  kubernetes.core.helm:
    name: kang-elastic
    chart_ref: /root/Elasticsearch/Elastic/eck-operator
    release_state: present
    values_files: "/root/Elasticsearch/Elastic/eck-operator/values.yaml"
    release_namespace: "elastic-system"
    create_namespace: true


- name: wait for the probes to be ready
  pause:
    seconds: 40


- name: Apply elastic manifest so it would be deployed
  kubernetes.core.k8s:
    src: "/root/Elasticsearch/Elastic/Elastic.yaml"
    state: present
    namespace: elastic-system
    apply: true
    kubeconfig: /etc/kubernetes/admin.conf


- name: wait for the pods to be ready
  pause:
    seconds: 50




