---
- name: Check for connectivity
  ping:
    data: alive


- name: pull k8s images
  command:
    cmd: kubeadm config images pull --v=5
  register: kubeadm_images
  changed_when: "'Image pull complete' in kubeadm_images.stdout"

- name: Display haproxy IP address
  debug:
    msg: "The IP address of the 'haproxy' host is {{ hostvars['haproxy']['ansible_host'] }}"


- name: Initialize Kubernetes master
  when: init_master == 'true'
  command:
    cmd: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --control-plane-endpoint {{ control_plane_endpoint }}:6443 --upload-certs --v=5
  register: kubeadm_init_result
  changed_when: "'Your Kubernetes control-plane has initialized successfully!' not in kubeadm_init_result.stdout"



- name: craete adirectory in $HOME/.kube/
  file:
    path: $HOME/.kube
    state: directory
    owner: root
    group: root
    mode: 0644


- name: copy kubernetes config to home
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    owner: root
    group: root
    mode: 0644
    remote_src: true




