apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kang-kibana
  namespace: elastic-system
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 8.9.1
  count: 1
  elasticsearchRef:
    name: kang-elastic
